import { faker } from "@faker-js/faker";

import {
    productOne,
    productTwo,
    productThree,
    productFour,
    productFive,
    productSix,
    productSeven,
    productEight,
    productNine,
    productTen,
    productEleven,
    productTwelve,
    productThirteen,
    productFourteen,
    productFifteen,
    productSixteen,
    productSeventeen,
    productEighteen,
    productNineteen,
    productTwenty,
    productTwentyOne,
    productTwentyTwo,
    productTwentyThree,
    productTwentyFour,
    productTwentyFive,
    productTwentySix,
    productTwentySeven,
    productTwentyEight,
} from "./images";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
    {
        _id: "e8assdd-sas5-4f76-b99e-sdfgfdg-74ff6576",
        name: "Satin Silver",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["indoor"],
        imgUrl: productTwentyFive,
        prodDesc: [
            "The Silver Satin vine, or Scindapsus pictus, is a low-maintenance plant that will add a bit of flair to any sill or shelf with its silvery variegation that catches and reflects light. Added bonus—it is easy to propagate a cutting of this plant in water!",
            "With its fleshy moss green leaves and silvery variegations the Satin Silver Splash is an easy to grow vining plant. The heart shaped leaves have a velvety texture and trail beautifully from long stems. They do great in bright to medium light and look especially stunning trailing down from shelves , add them to our gold monochrome ceramic planters and watch the magic.",
        ],
    },
    {
        _id: "e83-98gads-fhd1b8-0a75-4f76-b99e-c004e74f6576",
        name: "Bromeliad Antonio",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["flowering", "air purifying"],
        imgUrl: productTwentyOne,
        prodDesc: [
            "The “pink” in Bromeliad Antonio Pink describes the fuchsia bracts found in this cultivar, which sometimes produce short-blooming purple flowers. Its vibrant bract also gives it its nickname, the Pink Quill Plant. This plant is pet-friendly!",
            "This Bromeliad Tillandsia is amazing! Its pink flower looks like an Indian feather, hence its Spanish nickname and common name. The perfect gift or keep it to yourself for your home!",
        ],
    },
    {
        _id: "e8398gfhd1b8-0a75-4f76-b99e-c004e74f6576",
        name: "Hoya Heart",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["succulent"],
        imgUrl: productTwelve,
        prodDesc: [
            "What is better than a Heart Hoya? A heart hoya wit beautiful variegations. A slow-growing succulent with heart shaped leaves that are green with yellow creamy margins. The leaves grow in a cluster around the stems. A non-demanding and low-maintenance variety this makes for an excellent gifting option and is also great for new plant parents.",
            "The Hoya kerrii is commonly called the Hoya Heart because of its green heart-shaped leaves. This single leaf cutting is a fun, whimsical way to show your plant love. It is partially rooted but does not have a node. It will stay as an adorable heart-shaped leaf for years to come.",
        ],
    },
    {
        _id: "e8aqwewqed-sas5-4f76-b99e-c00784e74f6576",
        name: "Anthurium red",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["indoor", "air purifying"],
        imgUrl: productTwentyThree,
        prodDesc: [
            "Also known as the flamingo flower, the Anthurium is the world’s longest blooming houseplant. It is rarely without its showy blooms. These aren’t actual flowers, but modified waxy leaves that circle the pointed spadix, home to the plant's real, and very tiny, flowers. Each can last up to eight weeks—bringing a fun pop of color to your space year-round.",
            'The name of the genus comes from the Greek words anthos for "flower" and oura for "tail", which refers to the tail-shaped spadix. The Jungle King Anthurium has to rely on its large leaves, which give each interior a "touch of the jungle". This red Anthurium is an easy houseplant that can give you lots of fun for a long time!',
        ],
    },
    {
        _id: "e8asd-sas5-4f76-b99e-c004e74f6576",
        name: "ZZ Plant",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["succulent", "air purifying"],
        imgUrl: productSixteen,
        prodDesc: [
            "Topping the list of indestructible houseplants is the Zamioculcas Zamiifolia more popularly known as the ZZ plant. This plant is loved for his easy going and non-demanding nature. The wide, dark, glossy leaves instantly add life to any interior and he will be a happy trooper in the darkest corners of your home.",
            "The ZZ Plant is characterized by its waxy green leaves above the surface of its potting mix, and its large potato-like rhizomes underneath. These rhizomes store water, making the ZZ a hardy, drought-tolerant houseplant that only needs water every few weeks.",
        ],
    },
    {
        _id: "e83j981b8-0a75-4f76-b99e-c004e74f6576",
        name: "Fiddle Leaf Fig",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["indoor", "ficus"],
        imgUrl: productSeventeen,
        prodDesc: [
            "The coolest kid on the block at the moment and an Instagram superstar, the Ficus Lyrata or the Fiddle Leaf Fig is a tropical plant that is also a great air purifier. Give it a spot with enough light and proper watering and it will gift you with beautiful broad leaves that will make your space worthy of a magazine feature. Get it home.",
            "The Fiddle Leaf Fig is famous for its broad, vibrant green leaves with prominent veining. It prefers a stable environment and can be fickle when temps fluctuate. Keep it in bright light, and water about once every 1–2 weeks.",
        ],
    },
    {
        _id: "e83981b8-0a75-4f76-b99e-c004e74f6576",
        name: "Coffee Plant",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["indoor"],
        imgUrl: productOne,
        prodDesc: [
            "You might be surprised to know the same plant that grows your morning coffee beans is a popular, low-maintenance houseplant! Although it’s unlikely this plant will produce berries inside, its attractive shiny green foliage will liven up any interior space. ",
        ],
    },
    {
        _id: "e8cvn3981b8-0jka75-4f76-b99e-c004e74f6576",
        name: "Baby Rubber Plant",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["indoor", "air purifying"],
        imgUrl: productEighteen,
        prodDesc: [
            "The Peperomia obtusifolia, also known as the baby rubber plant, is an easy-going houseplant characterized by its thick, succulent-like green leaves. A popular variety of Peperomia, it does not need much to thrive and might even reward you with white flower spikes once a year. It is an attractive air purifier, with all of the same cherished characteristics.",
        ],
    },
    {
        _id: "e8as-sdd-sas5-4f76-b99e-sdfgfdg-74ff6576",
        name: "Ficus Tineke",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["ficus", "air purifying"],
        imgUrl: productTwentySix,
        prodDesc: [
            "The Ficus elastica ’Tineke’ – or variegated rubber tree – is a popular variety of ficus known for its beautiful pink, green, and yellow leaves. The Tineke’s striking variegation and easy-going nature make it the perfect new plant to add to your sill this year.",
            "Bring life into dull, empty corners with one of the prettiest houseplants, the Rubber Plant Variegated. Its leaves display stunning variegations in shades of cream, pink and green with red midribs. An air purifier that is as stunning as it gets and thrives with little care is an excellent addition to your space.",
        ],
    },
    {
        _id: "e83981b8-0a75-4f76-b99e-c004e7fgd4f6576",
        name: "Money Tree Plant",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["indoor", "bonsai"],
        imgUrl: productTwo,
        prodDesc: [
            "Said to bring good luck and fortune, the Money Tree is the perfect plant to add to any room of your home to create good Feng Shui. It is known for its resilience, ease of growth, and fun braided trunk. It is equal parts fuss-free and beautiful. With its braided stems and leaves that grow in sets of 5, the Money Tree makes a great centre piece. Make it a part of your indoor plant cluster or place it in empty room corners to add visual interest.",
        ],
    },
    {
        _id: "e83981dfgdfb8-0a75-4f76-b99e-c004e74f6576",
        name: "Philodendron Green",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["indoor"],
        imgUrl: productThree,
        prodDesc: [
            "The indoor house plant that has been in trend for generations now, the Philodendron Oxycardium Green can as well be called the original superstar of the plant world. Large glossy heart shaped leaves, flexible trailing vines that can be styled as you wish and easy and quick growing nature make it a must have. Let it trail on your walls with the help of wire clips or a trellis – and voila, you have yourself a Pinterest worthy wall.",
            "Why is the Philodendron our most popular plant year after year? It could be its heart-shaped green leaves, easy-going nature, or quick-growing trailing vines. Snag this low-maintenance houseplant now to bring life to your space during the winter months ahead.",
        ],
    },
    {
        _id: "e8asd-asdasd8-0a75-4f76-b99e-c004ehjg74f6576",
        name: "Bromeliad Vriesea",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["flowering", "air purifying"],
        imgUrl: productTwentyFour,
        prodDesc: [
            "This gorgeous rossette is a lively and colourful exhibition, playing with the shades of green, along with the vibrant cone-like blossom in a flirtatious pattern or red and yellow.",
            "The Bromeliad Vriesea Vogue is one of the most beautiful and distinctive pet-friendly plants, with a cone-like red and yellow spike that sometimes produces flowers. The colorful bract has earned this bromeliad the nickname Flaming Sword Plant.",
        ],
    },
    {
        _id: "e83981b8-0a75-4f76-b99e-c004erte74f6576",
        name: "Bird of Paradise",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["indoor"],
        imgUrl: productFour,
        prodDesc: [
            "With its broad vibrant green leaves, the Bird of Paradise brings a touch of the tropics to any room. It is named after its unique flowers which resemble brightly colored birds in flight. The Bird of Paradise thrives in warmer conditions with plenty of sunlight. Sized to ship best, our large Bird of Paradise arrives with room to grow as it adapts to your home’s conditions.",
            " A cousin of the banana family, it is one of the easier and more tolerant tropical plants to be grown at home. The plant can grow easily anywhere from bright direct light to semi-shade areas to reward you with graceful arching leaves that come out directly from the soil resembling a hand fan.",
        ],
    },
    {
        _id: "e8398sdfsdf1b8-0a75-4f76-b99e-c004erte74f6576",
        name: "Ric Rac Cactus",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["indoor", "cacti"],
        imgUrl: productTwenty,
        prodDesc: [
            "The Ric Rac Cactus will win over any plant parent: Not only is it pet-friendly and easy to care for, but it offers ric rac- or fishbone-shaped trailing stems and the occasional night-blooming flower. It is considered non-toxic, safe to keep around curious cats and dogs.",
            "Disocactus anguliger, commonly known as the fishbone cactus or zig zag cactus, is a cactus species native to Mexico. The species is commonly grown as an ornamental for its fragrant flowers in the fall.",
        ],
    },
    {
        _id: "e83981yikjhb8-0a75-4f76-b99e-c004e74f6576",
        name: "Snake Plant",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["succulent", "air purifying"],
        imgUrl: productFive,
        prodDesc: [
            "The Snake Plant Laurentii, or Sansevieria trifasciata 'Laurentii', is a succulent plant characterized by its upright sword-like leaves with vibrant yellow edges. It is popular for its incredibly easy-going nature – it can tolerate low light and drought – and its air-purifying capabilities. The easiest way to kill this plant is to overcare for it!",
            "It is an ornamental plant that grows in irregular rosette pattern. It does well in small pots even in low light conditions. It can add beautiful texture and elegance to your homes or even offices.",
        ],
    },
    {
        _id: "e8assdd-sas5-4f76-b99e-c004e74ff6576",
        name: "Prayer Plant",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["indoor", "air purifying"],
        imgUrl: productTwentyEight,
        prodDesc: [
            "The Calathea Orbifolia’s broad, oval-shaped leaves with contrasting green stripes make it a popular plant for home decor and plant enthusiasts alike. Its lush foliage benefits from frequent waterings and high humidity. In ideal conditions (think tropical), its pet-friendly leaves can grow over a foot wide!",
            "Calathea Orbifolia is the plant that will make you turn and look at it for the second time - although it almost always is love at first sight. With its oversized circular leaves striped with silver it’s not just an exquisite beauty but an excellent air purifier that is perfect for most spaces. It thrives in indirect light and is also pet friendly.",
        ],
    },
    {
        _id: "e83981b8-0a75-4f76-b99e-c004ehjg74f6576",
        name: "Swiss cheese plant",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["monstera", "air purifying"],
        imgUrl: productSix,
        prodDesc: [
            "Nicknamed the “swiss cheese plant”, the Monstera deliciosa is famous for its quirky natural leaf holes. These holes are theorized to maximize sun fleck capture on the forest floor. Depending on the season and maturity of the plant, your Monstera could arrive with no holes just yet, and be sized to grow alongside you.",
            "You might have seen it in a million home décor posts on social media, the absolute reigning king, the Monstera Deliciosa or the Swiss Cheese Plant is a tropical delight with shiny large leaves with fenestrations that make it unlike any plant ever. Its mere presence will add happiness and glamour to your home and it is so easy to care for.",
        ],
    },
    {
        _id: "e83-9833-gads-fhd1b8-0a75-4f76-b99e-c004e74f6576",
        name: "Anthurium Pink",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["indoor", "air purifying"],
        imgUrl: productTwentyTwo,
        prodDesc: [
            "Anthurium Pink or the Flamingo plant is a low-maintenance plant with heart-shaped red waxy blooms that last up to eight weeks. They bloom profusely for more than 250 days a year with bright indirect light and without any special attention and are the perfect size for any indoor area with their bright and shiny presence.",
            "This bright pink Anthurium lives up to its nickname, the flamingo flower. Rarely without their showy blooms, Anthuriums are known as the world’s longest blooming houseplant. Each bloom can last up to eight weeks, and new ones will pop up often. These aren’t actual flowers, but modified waxy leaves. Anthuriums flourish and bloom best in bright indirect light.",
        ],
    },
    {
        _id: "e83981ghjkb8-0a75-4f76-b99e-c004e74f6576",
        name: "Christmas Cactus",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["cacti", "flowering"],
        imgUrl: productSeven,
        prodDesc: [
            "True to their name, these flat leafed succulents bloom right in time for the holiday season and that too profusely. The pretty pink blooms last well into the new year and when not blooming they make for a pretty foliage plant. Requiring very little care other than bright light, they are excellent for those sunny windows of yours",
            "There’s something wonderfully nostalgic about the Holiday Cactus. Also called the Thanksgiving Cactus, Christmas Cactus, or Easter Cactus—depending on bloom time and leaf shape—the pet-safe Schlumbergera is a favorite winter succulent. This plant ships in different stages of its bloom cycle and can arrive without buds. The color of its flowers vary: pink, red, white, or lavender.",
        ],
    },
    {
        _id: "e83981457b8-0a75-4f76-b99e-c004e74f6576",
        name: "Parlor Palm",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["air purifying"],
        imgUrl: productEight,
        prodDesc: [
            "The Parlor Palm is a favorite easy-care palm with tropical fronds known for its air-purifying qualities.",
            "Once an endangered species, the Areca Palm is a staple in Indian spaces. One of the most undervalued plants in the indoor plant category. This excellent air purifier is pet friendly and easy to grow. Its delicate leaves/fronds grow outwards in a curved manner and add a tropical feel to any space and can adapt to a variety of growing conditions.",
        ],
    },
    {
        _id: "e83981b8-0a75-4ftyutyu76-b99e-c004e74f6576",
        name: "Ficus Bonsai",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["bonsai", "ficus"],
        imgUrl: productNine,
        prodDesc: [
            "The Ficus Bonsai, commonly known as the Weeping Fig or Ficus Tree is a beautiful houseplant which is loved by numerous plant parents. It has a unique curved trunk with dark green, oval leaves making it a brilliant centre piece for your living room or side table. Plant them in shallow but wide pots to show if its magnificent stem and roots.",
        ],
    },
    {
        _id: "e8398sdfsfd45-7b8-0a75-4f76-b99e-c004e74f6576",
        name: "Rubber plant",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["air purifying", "ficus"],
        imgUrl: productNineteen,
        prodDesc: [
            "The Ficus Burgundy, or rubber tree, is known for its glossy burgundy leaves and latex sap that was once used in rubber production! This same sap makes the Ficus elastica toxic, so the best practice is to keep it out of the reach of curious pets and small children. Give your Ficus Burgundy plenty of bright indirect light to help it retain its dramatic foliage.",
            "With its dark glossy leaves, the rubber plant is a crowd favourite of both designers and home gardeners alike. An excellent choice for an air purifying as well as an ornamental plant, it thrives in the Indian climate and can live for almost a decade with proper care, which is very little in the first place. Get it home and watch it grow with you.",
        ],
    },
    {
        _id: "e83981b8-0atyuyt75-4f76-b99e-c004e74f6576",
        name: "White Orchid",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["flowering", "indoor"],
        imgUrl: productTen,
        prodDesc: [
            "Affectionately nicknamed the beginner orchid, the popular Phalaenopsis orchid is one of the easiest varieties of orchids to grow as a houseplant. This orchid will typically bloom once a year for up to three months. Upon delivery, you may notice a small amount of blooms on your orchid – these blooms will open quicker in a warm, indoor setting. After a blooming cycle, the flowers will wilt and fall off and the orchid will store up energy to re-bloom again next season.",
            "The saying “A thing of beauty is a joy forever” has never been truer than in the case of orchids. One of the most exotic flowers to grace our homes, the orchids are finicky in their care but reward you with sweet-smelling flowers that last a long while. These white orchids will turn your home into a winter wonderland in no time.",
        ],
    },
    {
        _id: "e83981b8-0a75-4f76-b99e-c004e74frtyuer6576",
        name: "Pink Orchid",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["flowering", "indoor"],
        imgUrl: productEleven,
        prodDesc: [
            "Add a pop of pink to your tablescape with this popular Phalaenopsis orchid. One of the easiest varieties to grow as a houseplant, it is affectionately called the beginner orchid. You may notice a small amount of blooms on your orchid upon delivery. These blooms will open quicker in a warm indoor setting. It will typically bloom about once a year, for up to three months. After a blooming cycle, the flowers will wilt and fall off. This is the orchid’s way to store up energy to re-bloom again next season.",
        ],
    },
    {
        _id: "e83981fdhfghb8-0a75-4f76-b99e-c004e74f6576",
        name: "Echeveria Lola",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["succulent", "air purifying"],
        imgUrl: productThirteen,
        prodDesc: [
            "The greenest and cutest member of the “Hens and Chicks” family of succulents, the Sempervivum calcareum variety grows in a happy bunch with numerous offsets that spring up from the mother plant in no time. It grows in neat small colonies in bright sun to proudly show off its dark red tips contrasting with the lemon green leaves. The plant can survive through extreme cold and just needs protection from standing water.",
            "The Echeveria is our equivalent of the rose. This iconic succulent has fleshy drought-tolerant green leaves that grow in a chic rosette shape. It’s the perfect pick-me-up plant for yourself or a friend. ",
        ],
    },
    {
        _id: "e839fdhdfgh81b8-0a75-4f76-b99e-c004e74f6576",
        name: "Broken Heart Plant",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["monstera", "air purifying"],
        imgUrl: productFourteen,
        prodDesc: [
            "One of the most popular houseplants, this easy growing plant with its heart shaped leaves that have holes in the leaf blade is a crowd favourite. Quick to grow with delicate trailing vines that can be styled for every space, the Philodendron broken heart will add an instant tropical feel and charm to your space. The Swiss Cheese Plant also boasts soft yet resilient stems that can be trained to climb, hang, or trail.",
        ],
    },
    {
        _id: "e832342h4b8-0a75-4f76-b99e-cfdhdfh004e74f6576",
        name: "Philodendron Birkin",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["indoor"],
        imgUrl: productTwentySeven,
        prodDesc: [
            "The Philodendron Birkin is characterized by its lush green leaves with white or yellow pinstripes. A unique hybrid, you won't find this plant in the wild. It is a slow-growing plant that can reach up to 3 feet tall indoors if well cared for.",
            "Philodendrons are one of the most loved and widely grown indoor plant species in the world, but what is better than a regular philodendron is a variegated one. The birkin has a stunning dark green colour with elegant white variegations resembling fish bone. The leaves are glossy and heart shaped and ovate and bring an interesting charm to any space.",
        ],
    },
    {
        _id: "e83981b8-0a75-4f76-b99e-cfdhdfh004e74f6576",
        name: "Adanson's monstera",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["monstera"],
        imgUrl: productFifteen,
        prodDesc: [
            "Monstera Adansonii are known for their lacy green leaves, covered with natural leaf-holes called fenestrations. The Adanson's monstera also boasts soft yet resilient stems that can be trained to climb, hang, or trail. Sized to ship best, our large Monstera Adansonii arrives with room to grow as it adapts to your home’s conditions.",
        ],
    },
];
