import { faker } from "@faker-js/faker";

import {
    productOne,
    productTwo,
    productThree,
    productFour,
    productFive,
    productSix,
    productSeven,
    productEight,
    productNine,
    productTen,
    productEleven,
    productTwelve,
    productThirteen,
    productFourteen,
    productFifteen,
} from "./images";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
    {
        id: faker.datatype.uuid(),
        name: "Coffee Plant",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["indoor"],
        imgUrl: productOne,
    },
    {
        id: faker.datatype.uuid(),
        name: "Money Tree Plant",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["indoor", "bonsai"],
        imgUrl: productTwo,
    },
    {
        id: faker.datatype.uuid(),
        name: "Philodendron Green",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["indoor"],
        imgUrl: productThree,
    },
    {
        id: faker.datatype.uuid(),
        name: "Bird of Paradise",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["indoor"],
        imgUrl: productFour,
    },
    {
        id: faker.datatype.uuid(),
        name: "Snake Plant",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["succulent", "indoor"],
        imgUrl: productFive,
    },
    {
        id: faker.datatype.uuid(),
        name: "Swiss cheese plant",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["monstera", "air purifying"],
        imgUrl: productSix,
    },
    {
        id: faker.datatype.uuid(),
        name: "Christmas Cactus",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["cacti", "flowering"],
        imgUrl: productSeven,
    },
    {
        id: faker.datatype.uuid(),
        name: "Parlor Palm",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["air purifying"],
        imgUrl: productEight,
    },
    {
        id: faker.datatype.uuid(),
        name: "Ficus Bonsai",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["bonsai"],
        imgUrl: productNine,
    },
    {
        id: faker.datatype.uuid(),
        name: "White Orchid",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["flowering", "indoor"],
        imgUrl: productTen,
    },
    {
        id: faker.datatype.uuid(),
        name: "Pink Orchid",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["flowering", "indoor"],
        imgUrl: productEleven,
    },
    {
        id: faker.datatype.uuid(),
        name: "Hoya Heart",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["succulent"],
        imgUrl: productTwelve,
    },
    {
        id: faker.datatype.uuid(),
        name: "Echeveria Lola",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["succulent", "air purifying"],
        imgUrl: productThirteen,
    },
    {
        id: faker.datatype.uuid(),
        name: "Broken Heart Plant",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["monstera", "air purifying"],
        imgUrl: productFourteen,
    },
    {
        id: faker.datatype.uuid(),
        name: "Adanson's monstera",
        rating: faker.datatype.number({ min: 1, max: 5 }),
        price: faker.datatype.number({ min: 240, max: 1599 }),
        type: ["monstera"],
        imgUrl: productFifteen,
    },
];
